version: '3.7'

services:     
  postgres:
    container_name: postgres-teplo
    hostname: postgres
    image: postgres:12.7
    environment:
      POSTGRES_PASSWORD: postgresroot
      POSTGRES_USER: postgres
      POSTGRES_DB: teplo
    ports:
      - "0.0.0.0:5432:5432"

  api:
    container_name: teplo-api
    hostname: api
    build: ./TeploAPI
    ports:
      - "0.0.0.0:5004:5004"

  frontend:
    build: ./teplo-client
    ports:
      - 3000:3000
    depends_on:
      - api